// Created by iWeb 3.0.4 local-build-20250228

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWPhotoFrame([IWCreateImage('STAR_TREK_Ornaments_files/Formal_inset_01.png'),IWCreateImage('STAR_TREK_Ornaments_files/Formal_inset_02.png'),IWCreateImage('STAR_TREK_Ornaments_files/Formal_inset_03.png'),IWCreateImage('STAR_TREK_Ornaments_files/Formal_inset_06.png'),IWCreateImage('STAR_TREK_Ornaments_files/Formal_inset_09.png'),IWCreateImage('STAR_TREK_Ornaments_files/Formal_inset_08.png'),IWCreateImage('STAR_TREK_Ornaments_files/Formal_inset_07.png'),IWCreateImage('STAR_TREK_Ornaments_files/Formal_inset_04.png')],null,0,0.800000,1.000000,1.000000,1.000000,1.000000,14.000000,14.000000,14.000000,14.000000,191.000000,262.000000,191.000000,262.000000,null,null,null,0.100000),stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,49),url:'STAR_TREK_Ornaments_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'STAR_TREK_Ornaments_files/stroke_1.png'},{rect:new IWRect(2,-2,83,4),url:'STAR_TREK_Ornaments_files/stroke_2.png'},{rect:new IWRect(85,-2,4,4),url:'STAR_TREK_Ornaments_files/stroke_3.png'},{rect:new IWRect(85,2,4,49),url:'STAR_TREK_Ornaments_files/stroke_4.png'},{rect:new IWRect(85,51,4,5),url:'STAR_TREK_Ornaments_files/stroke_5.png'},{rect:new IWRect(2,51,83,5),url:'STAR_TREK_Ornaments_files/stroke_6.png'},{rect:new IWRect(-2,51,4,5),url:'STAR_TREK_Ornaments_files/stroke_7.png'}],new IWSize(87,53))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('STAR_TREK_Ornaments_files/STAR_TREK_OrnamentsMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');fixAllIEPNGs('Media/transparent.gif');applyEffects()}
