// Created by iWeb 3.0.4 local-build-20250228

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWPhotoFrame([IWCreateImage('DOLL_FURNITURE_%26_ACCESSORIES_files/Formal_inset_01.png'),IWCreateImage('DOLL_FURNITURE_%26_ACCESSORIES_files/Formal_inset_02.png'),IWCreateImage('DOLL_FURNITURE_%26_ACCESSORIES_files/Formal_inset_03.png'),IWCreateImage('DOLL_FURNITURE_%26_ACCESSORIES_files/Formal_inset_06.png'),IWCreateImage('DOLL_FURNITURE_%26_ACCESSORIES_files/Formal_inset_09.png'),IWCreateImage('DOLL_FURNITURE_%26_ACCESSORIES_files/Formal_inset_08.png'),IWCreateImage('DOLL_FURNITURE_%26_ACCESSORIES_files/Formal_inset_07.png'),IWCreateImage('DOLL_FURNITURE_%26_ACCESSORIES_files/Formal_inset_04.png')],null,0,0.800000,1.000000,1.000000,1.000000,1.000000,14.000000,14.000000,14.000000,14.000000,191.000000,262.000000,191.000000,262.000000,null,null,null,0.100000)});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('DOLL_FURNITURE_&_ACCESSORIES_files/DOLL_FURNITURE_&_ACCESSORIESMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');fixAllIEPNGs('Media/transparent.gif');IMpreload('DOLL_FURNITURE_&_ACCESSORIES_files','shapeimage_5','0');IMpreload('DOLL_FURNITURE_&_ACCESSORIES_files','shapeimage_11','0');IMpreload('DOLL_FURNITURE_&_ACCESSORIES_files','shapeimage_12','0');IMpreload('DOLL_FURNITURE_&_ACCESSORIES_files','shapeimage_13','0');IMpreload('DOLL_FURNITURE_&_ACCESSORIES_files','shapeimage_14','0');IMpreload('DOLL_FURNITURE_&_ACCESSORIES_files','shapeimage_15','0');IMpreload('DOLL_FURNITURE_&_ACCESSORIES_files','shapeimage_16','0');IMpreload('DOLL_FURNITURE_&_ACCESSORIES_files','shapeimage_17','0');IMpreload('DOLL_FURNITURE_&_ACCESSORIES_files','shapeimage_18','0');IMpreload('DOLL_FURNITURE_&_ACCESSORIES_files','shapeimage_19','0');IMpreload('DOLL_FURNITURE_&_ACCESSORIES_files','shapeimage_20','0');IMpreload('DOLL_FURNITURE_&_ACCESSORIES_files','shapeimage_21','0');IMpreload('DOLL_FURNITURE_&_ACCESSORIES_files','shapeimage_24','0');IMpreload('DOLL_FURNITURE_&_ACCESSORIES_files','shapeimage_25','0');IMpreload('DOLL_FURNITURE_&_ACCESSORIES_files','shapeimage_26','0');IMpreload('DOLL_FURNITURE_&_ACCESSORIES_files','shapeimage_27','0');IMpreload('DOLL_FURNITURE_&_ACCESSORIES_files','shapeimage_28','0');IMpreload('DOLL_FURNITURE_&_ACCESSORIES_files','shapeimage_30','0');IMpreload('DOLL_FURNITURE_&_ACCESSORIES_files','shapeimage_31','0');IMpreload('DOLL_FURNITURE_&_ACCESSORIES_files','shapeimage_32','0');fixupIECSS3Opacity('id5');IMpreload('DOLL_FURNITURE_&_ACCESSORIES_files','shapeimage_34','0');IMpreload('DOLL_FURNITURE_&_ACCESSORIES_files','shapeimage_35','0');IMpreload('DOLL_FURNITURE_&_ACCESSORIES_files','shapeimage_36','0');applyEffects()}
