// Created by iWeb 3.0.4 local-build-20250228

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWPhotoFrame([IWCreateImage('Copy_Lace,_Braid,_Venise,_Fabric,_Ruffles,_Ribbon_2_files/Formal_inset_01.png'),IWCreateImage('Copy_Lace,_Braid,_Venise,_Fabric,_Ruffles,_Ribbon_2_files/Formal_inset_02.png'),IWCreateImage('Copy_Lace,_Braid,_Venise,_Fabric,_Ruffles,_Ribbon_2_files/Formal_inset_03.png'),IWCreateImage('Copy_Lace,_Braid,_Venise,_Fabric,_Ruffles,_Ribbon_2_files/Formal_inset_06.png'),IWCreateImage('Copy_Lace,_Braid,_Venise,_Fabric,_Ruffles,_Ribbon_2_files/Formal_inset_09.png'),IWCreateImage('Copy_Lace,_Braid,_Venise,_Fabric,_Ruffles,_Ribbon_2_files/Formal_inset_08.png'),IWCreateImage('Copy_Lace,_Braid,_Venise,_Fabric,_Ruffles,_Ribbon_2_files/Formal_inset_07.png'),IWCreateImage('Copy_Lace,_Braid,_Venise,_Fabric,_Ruffles,_Ribbon_2_files/Formal_inset_04.png')],null,0,0.800000,1.000000,1.000000,1.000000,1.000000,14.000000,14.000000,14.000000,14.000000,191.000000,262.000000,191.000000,262.000000,null,null,null,0.100000)});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Copy_Lace,_Braid,_Venise,_Fabric,_Ruffles,_Ribbon_2_files/Copy_Lace,_Braid,_Venise,_Fabric,_Ruffles,_Ribbon_2Moz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');fixAllIEPNGs('Media/transparent.gif');IMpreload('Copy_Lace,_Braid,_Venise,_Fabric,_Ruffles,_Ribbon_2_files','shapeimage_2','0');IMpreload('Copy_Lace,_Braid,_Venise,_Fabric,_Ruffles,_Ribbon_2_files','shapeimage_4','0');IMpreload('Copy_Lace,_Braid,_Venise,_Fabric,_Ruffles,_Ribbon_2_files','shapeimage_5','0');IMpreload('Copy_Lace,_Braid,_Venise,_Fabric,_Ruffles,_Ribbon_2_files','shapeimage_7','0');IMpreload('Copy_Lace,_Braid,_Venise,_Fabric,_Ruffles,_Ribbon_2_files','shapeimage_9','0');applyEffects()}
